[build]
# Use nixpacks for PHP detection
nixpacks = true

[deploy]
# Start command for PHP built-in server
startCommand = "php -S 0.0.0.0:$PORT"

[variables]
# Railway will automatically load these from your dashboard
# But you can also define defaults here
PORT = "8080"
APP_ENV = "production"
DEBUG_MODE = "false"